<?php
$title = $this->translate("Job function");
$this->title = $title . ' - ' . $this->translate("Delete");
$this->headTitle($this->translate("Job function"));
?>

<div class="container widget-content">
    <?php echo $this->form->setAction($this->url()); ?>
    <p class="alert alert-block">
        <i class="icon-info-sign"></i> <translate>Your are about to delete a record. If you confirm, all it´s data and the related data will be deleted. If any record related to this user should not be deleted from here, you will receive a warning and this action will be canceled.</translate>
    </p>

</div>