<?php
$title = $this->translate("Volunteer");
$this->title = $title;
$this->headTitle($this->translate("Volunteer"));
?>

<div class="window">
    <div class="window-header">
        <h3 class="pull-left"><i class="icon-group"></i> <translate>Volunteers</translate></h3>
        <ul class="nav nav-pills hidden-print pull-right">
            <li>
                <a title="<translate>Print this page</translate>" rel="print-window" href="#">
                    <i class="icon-print"></i> 
                    <translate>Print</translate>
                </a>
            </li>
        </ul>
    </div>
    <div class="window-content">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th><translate>Name</translate></th>
            <th><translate>Expertise areas</translate></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->volunteers as $acc) {
                    $edit = $this->url(
                            array('module' => 'staff', 'controller' => 'volunteer',
                        'action' => 'update', 'id' => $acc->id), null, true);

                    $delete = $this->url(
                            array('module' => 'staff', 'controller' => 'volunteer',
                        'action' => 'delete', 'id' => $acc->id), null, true);

                    $details = $this->url(
                            array('module' => 'persons', 'controller' => 'person',
                        'action' => 'getgm', 'id' => $acc->id), null, true);
                    ?>
                    <tr>
                        <td><?php echo $acc->id; ?></td>
                        <td><?php echo $acc->getPerson()->name; ?></td>
                        <td><?php
                            foreach ($acc->getExpertisearea() as $exp) {
                                        echo $exp->name . ', ';                    
                            }
                    ?></td>

                        <td class='align_center hidden-print'>
                            <a class="btn btn-mini btn-primary" href="<?php echo $details; ?>" load-in="content-container">
                                <i class="icon-search"></i> <translate>Person details</translate>
                            </a>
                            <a class="btn btn-mini btn-info" href="<?php echo $edit; ?>" load-in="content-container">
                                <i class="icon-edit"></i> <translate>Edit</translate>
                            </a>
                            <a class="btn btn-mini btn-danger" href="<?php echo $delete; ?>" load-in="content-container">
                                <i class="icon-remove-sign"></i> <translate>Delete</translate>
                            </a>                    
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>