<?php
$title = $this->translate("Persons");
$this->title = $title;
$this->headTitle($this->translate("Persons"));
?>

<div class="window">
    <div class="window-header">
        <h3 class="span2"><i class="icon-user-md"></i> <translate>Persons</translate></h3>

        <form class="pull-right hidden-print" action="<?= $this->url(); ?>" load-in="content-container">
            <div class="input-append">
                <input type="text" 
                       value="<?= $this->filter_keyword; ?>" 
                       placeholder="<translate>Filter by</translate>" 
                       class="input-medium" name="filter-keyword"/>
                <button type="submit" class="btn"><i class="icon-refresh"></i></button>
                <a href="#searchHelp" class="btn add-on" data-toggle="modal"><i class="icon-question-sign"></i></a>
            </div>
        </form>

        <!-- Search help -->
        <div id="searchHelp" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">Ajuda para pesquisa / filtro</h3>
            </div>
            <div class="modal-body">
                <p>
                    Ao preencher campos de pesquisa ou filtro de listagens é possível 
                    utilizar caracteres chamados "coringas", que auxiliam na abrangência de
                    resultados.
                </p>
                <p>
                    O caracter <strong>%</strong> (percentual) pode ser utilizado 
                    para substituir conjuntos de letras em posições determinadas.
                </p>
                <p>
                    Exemplos de uso:
                </p>
                <dl>
                    <dt>Pesquisa exata</dt>
                    <dd>
                        <p>
                            Não utilizar nenhum coringa força uma busca pelo conjunto
                            exato de dados passados no campo de filtro. Exemplos:
                        </p>
                        <ol>
                            <li class="alert alert-info">
                                Filtro: <strong>Carlos</strong> <br/>
                                Retorno: apenas os registros que tenham exatamente o valor <strong>Carlos</strong>
                            </li>
                            <li class="alert alert-info">
                                Filtro: <strong>Carlos Pereira</strong> <br/>
                                Retorno: apenas os registros que tenham exatamente o valor <strong>Carlos Pereira</strong>
                            </li>
                            <li class="alert alert-info">
                                Filtro: <strong>Carlos &nbsp;&nbsp; Pereira</strong> (com mais de um espaço entre os nomes)<br/>
                                Retorno: apenas os registros que tenham exatamente o valor com dois espaços ou nenhum valor
                            </li>
                        </ol>
                    </dd>
                    <dt>Pesquisa por frases que iniciam com ...</dt>
                    <dd>
                        <p>
                            Utilizar um coringa (%) no final do campo de filtro. 
                            A busca retorna todos os registros que iniciam com os
                            dados digitados <em>antes</em> do coringa. 
                            Exemplos:
                        </p>
                        <ol>
                            <li class="alert alert-info">
                                Filtro: <strong>Carlos%</strong> <br/>
                                Retorno: os registros que iniciam com o valor <strong>Carlos</strong>: 
                                Carlos Antonio, Carlos Pereira, Carlos da Silva Amadeu
                            </li>
                        </ol>
                    </dd>
                    <dt>Pesquisa por frases que terminam com ...</dt>
                    <dd>
                        <p>
                            Utilizar um coringa (%) no início do campo de filtro. 
                            A busca retorna todos os registros que terminam com os
                            dados digitados <em>após</em> do coringa. 
                            Exemplos:
                        </p>
                        <ol>
                            <li class="alert alert-info">
                                Filtro: <strong>%Silva</strong> <br/>
                                Retorno: os registros que terminam com o valor <strong>Silva</strong>: 
                                José Silva, Maria Antonieta da Silva, Marcos Andressilva
                            </li>
                        </ol>
                    </dd>
                    <dt>Pesquisa por frases que contenham ...</dt>
                    <dd>
                        <p>
                            Utilizar um coringa (%) no início e no final 
                            do campo de filtro. 
                            A busca retorna todos os registros que contenham os
                            dados digitados <em>entre</em> os coringas. Não importando
                            o local da informação correspondente na frase.
                            Exemplos:
                        </p>
                        <ol>
                            <li class="alert alert-info">
                                Filtro: <strong>%Silva%</strong> <br/>
                                Retorno: os registros que contenham o valor <strong>Silva</strong>: 
                                Antonio Silva Andrade, José Silva, 
                                Maria Antonieta da Silva, Marcos Andressilva, 
                                Paulo da Silva Pedroso
                            </li>
                        </ol>
                    </dd>
                </dl>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
            </div>
        </div>

        <ul class="nav nav-pills hidden-print pull-right">
            <li>
                <a load-in="content-container" 
                   href="<?=
                   $this->url(array('module' => 'persons', 'controller' => 'person',
                       'action' => 'create'), null, true);
                   ?>">
                    <i class="icon-plus-sign"></i> <translate>Add new</translate>
                </a>
            </li>
            <li>
                <a title="<translate>Print this page</translate>" rel="print-window" href="#">
                    <i class="icon-print"></i> 
                    <translate>Print</translate>
                </a>
            </li>
        </ul>
    </div>
    <div class="window-content window-table">
        <table class="table table-striped table-hover" rel="click-row" data-click-row-selector=".btn-details">
            <thead>
                <tr>
                    <th>id</th>
                    <th><translate>Name</translate></th>
            <th><translate>Email</translate></th>
            <th><translate>Categoria</translate></th>
            <th><translate>Phone</translate></th>
            <th class="hidden-print"></th>
            </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->persons as $rec) {

                    $acc = is_object($rec) ? $rec : new Persons_Model_Person($rec);
                    $acc2 = is_object($rec) ? $rec : new Persons_Model_Employee($rec);
                    $acc3 = is_object($rec) ? $rec : new Persons_Model_Volunteer($rec);
                    $acc4 = is_object($rec) ? $rec : new Persons_Model_PersonHelped($rec);
                    $edit = $this->url(
                            array('module' => 'persons', 'controller' => 'person',
                        'action' => 'getgm', 'id' => $acc->id), null, true);
                    ?>

                    <tr>
                        <td><?php echo $acc->id; ?></td>
                        <td><?php echo $acc->name; ?></td>
                        <td><?php echo $acc->email; ?></td>
                        <td><?php
                            if ($acc2->job_function_id) {
                                echo "Funcionário ";
                            }
                            if ($acc3->id) {
                                echo "Voluntário";
                            }
                            if ($acc4->id) {
                                echo "Assistido";
                            }
                            ?></td>
                        <td>
                            <?php
                            echo $acc->phone;
                            echo (trim($acc->getMobilephone())) ?
                                    ((trim($acc->getPhone())) ? ' || ' : '') . $acc->getMobilephone() : '';
                            ?>
                        </td>
                        <td class='align_center hidden-print'>
                            <a class="btn btn-mini btn-info btn-details hidden-print" load-in="content-container"
                               href="<?php echo $edit; ?>" load-in="content-container">
                                <i class="icon-edit"></i> <translate>Details</translate>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>

        <?php
        if ($this->persons instanceof Zend_Paginator) {
            echo $this->paginationControl(
                    $this->persons, 'Sliding', array('/paginator/search.phtml', 'aganacore'), array('filter_keyword' => $this->filter_keyword)
            );
        }
        ?>
    </div>
</div>

