<?php
$title = 'Atendimentos realizados para ' . $this->person_helped->getPerson()->getName();
$this->title = $title;
$this->headTitle($this->title);

$urlNewEventActivity = $this->url(
        array('module' => 'assistance', 'controller' => 'activity',
    'action' => 'create', 'person-helped' => $this->person_helped->getId()), null, true);
?>

<div class="window">
    <div class="window-header">
        <span class="span9"><h3 ><i class="icon-food"></i> <?= $title ?></h3></span>
    </div>
    <div class="window-content">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>id</th>
                    <th>Data</th>
                    <th>Hora</th>
                    <th>Tipo de Tarefa</th>
                    <th>Projeto</th>
                    <th></th>
                    <th></th>
            <th class="hidden-print"></th>
            </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->activities as $act) {
                    if (is_array($act)) { $act = new Assistance_Model_Activity($act); }
                    
                    $edit = $this->url(
                            array('module' => 'assistance', 'controller' => 'activity',
                        'action' => 'update', 'id' => $act->id), null, true);

                    $delete = $this->url(
                            array('module' => 'assistance', 'controller' => 'activity',
                        'action' => 'delete', 'id' => $act->id), null, true);
                    
                    $urlGetPersonHelped = $this->url(
                            array('module' => 'persons', 'controller' => 'person',
                        'action' => 'getgm', 'id' => $act->person_helped_id), null, true);

                ?>
                <tr>
                    <td><?= $act->id; ?></td>
                    <td><?= $this->date($act->assistance_date, Zend_Date::DATE_MEDIUM); ?></td>
                    <td><?= substr($act->assistance_time,0,5); ?></td>
                    <td>
                        <?php 
                        $taskName = '';
                        if (intval($act->getTask_type()->getParent_id())>0) {
                            $parentName = $act->getTask_type()->getParent()->getName();
                            $taskName .= $parentName . ' :: ' ;
                        }
                        $taskName .= $act->getTask_type()->getName(); 
                        echo $taskName;
                        ?>
                    </td>
                    <td><?= $act->getProject()->getName(); ?></td>
                    <td class='align_center hidden-print'>
                        <!--
                        <a class="btn btn-mini btn-info" href="<?php echo ''//$edit; ?>" load-in="content-container">
                            <i class="icon-edit"></i> <translate>Edit</translate>
                        </a>

                        <a class="btn btn-mini btn-danger" href="<?php echo ''; //$delete; ?>" load-in="content-container">
                            <i class="icon-remove-sign"></i> <translate>Delete</translate>
                        </a>
                        -->
                    </td>
                    <td>
                        <?php
                        if ($act->getDescription()) {
                            ?>
                        <span class="badge badge-info" rel="popover" 
                              data-content="<?= nl2br($act->getDescription()) ?>"
                              data-placement="left"
                              data-html="true">
                            Descrição                            
                        </span>
                        <?php } ?>
                    </td>
                    <td>
                        <?= $this->identifiedByWidget($act->getId_by_finger_key()) ?>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>