<?php
$this->title = "Janela Principal";
?>

<div class="window">

    <h2 class="window-header">Bem vindo !!</h2>
    <div class="window-content">
        <p>
            Este é o aplicativo de gerenciamento de bem-estar, chamado Health Studio Manager.
        </p>
        <p>
            Por favor, utilize o menu para navegar nas funcionalidades desejadas.
        </p>
        <p>
            Equipe <a href="http://www.winponta.com.br" target="_blank">Winponta</a>
        </p>
    </div>
</div>