import com.nitgen.SDK.BSP.NBioBSPJNI;

public class NBioAPI_JavaDemo extends javax.swing.JDialog {

    /** Creates new form NBioAPI_JavaDemo */
    public NBioAPI_JavaDemo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent e) {
                Closing();
                System.exit(0);
            }
        });

        bsp = new NBioBSPJNI();

        if (CheckError())
            return ;

       setTitle("NBioAPI_JavaDemo BSP version: " + bsp.GetVersion());

       NBioBSPJNI.INIT_INFO_0 initInfo0 = bsp.new INIT_INFO_0();
       bsp.GetInitInfo(initInfo0);

       if (CheckError())
            return ;

       editEIQ.setText("" + initInfo0.EnrollImageQuality);
       editVIQ.setText("" + initInfo0.VerifyImageQuality);
       editMaxFinger.setText("" + initInfo0.MaxFingersForEnroll);
       editSPFinger.setText("" + initInfo0.SamplesPerFinger);
       editDTimeout.setText("" + initInfo0.DefaultTimeout);
       comboSLevel.setSelectedIndex(initInfo0.SecurityLevel - 1);

       btnGet.setEnabled(true);
       btnSet.setEnabled(true);
       btnOpen.setEnabled(true);

       if (SetDeviceList() == false)
          return ;

       rbtnHFIR.setSelected(true);

       labelStatus.setText("NBioBSP Initialize success");
    }

    public Boolean CheckError()
    {
        if (bsp.IsErrorOccured())  {
            labelStatus.setText("NBioBSP Error Occured [" + bsp.GetErrorCode() + "]");
            return true;
        }

        return false;
    }

    public void dispose()
    {
        if (hSavedFIR != null)  {
            hSavedFIR.dispose();
            hSavedFIR = null;
        }

        if (fullSavedFIR != null)
            fullSavedFIR = null;

        if (textSavedFIR != null)
            textSavedFIR = null;

        if (bsp != null) {
            bsp.dispose();
            bsp = null;
        }
    }

    public void Closing()
    {
        dispose();
    }

    private boolean SetDeviceList()
    {
        int i, n;
        String szValue;

        deviceEnumInfo = bsp.new DEVICE_ENUM_INFO();
        bsp.EnumerateDevice(deviceEnumInfo);

        if (CheckError())  {
           btnOpen.setEnabled(false);
           return false;
        }

        n = deviceEnumInfo.DeviceCount;

        if (n == 0)  {
            labelStatus.setText("Can not find Device!!");
            btnOpen.setEnabled(false);
            return false;
        }

        szValue = "Auto_Detect";
        comboDevice.addItem(szValue);

        for (i = 0; i < n; i++)  {
            szValue = deviceEnumInfo.DeviceInfo[i].Name + "(ID: " + deviceEnumInfo.DeviceInfo[i].Instance + ")";
            comboDevice.addItem(szValue);
        }

        comboDevice.setSelectedIndex(0);
        btnOpen.setEnabled(true);
        openedDevice = 0;
        
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFIRType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editEIQ = new javax.swing.JTextField();
        btnGet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        editVIQ = new javax.swing.JTextField();
        btnSet = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        editMaxFinger = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editSPFinger = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        editDTimeout = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboSLevel = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboDevice = new javax.swing.JComboBox();
        btnOpen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        editPayload = new javax.swing.JTextField();
        btnEnroll = new javax.swing.JButton();
        btnCapture = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        rbtnBFIR = new javax.swing.JRadioButton();
        rbtnTFIR = new javax.swing.JRadioButton();
        rbtnHFIR = new javax.swing.JRadioButton();
        btnVerify = new javax.swing.JButton();
        btnVerifyMatch = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BSP Information"));

        jLabel1.setText("Enroll Image Quality");

        editEIQ.setText("50");

        btnGet.setText("GET");
        btnGet.setEnabled(false);
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        jLabel2.setText("Verify Image Quality");

        editVIQ.setText("30");

        btnSet.setText("SET");
        btnSet.setEnabled(false);
        btnSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetActionPerformed(evt);
            }
        });

        jLabel3.setText("Max Finger");

        editMaxFinger.setText("10");

        jLabel4.setText("SamplesPerFinger");

        editSPFinger.setEditable(false);
        editSPFinger.setText("2");

        jLabel5.setText("Default Timeout");

        editDTimeout.setText("10000");

        jLabel6.setText("Security Level");

        comboSLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lowest", "Lower", "Low", "Below Normal", "Normal", "Above Normal", "High", "Higher", "Highest" }));
        comboSLevel.setSelectedIndex(4);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(btnSet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(editEIQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(34, 34, 34)
                                .add(btnGet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                .add(jLabel4)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(editSPFinger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                .add(editMaxFinger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jPanel1Layout.createSequentialGroup()
                                    .add(jLabel2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(editVIQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel5)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(comboSLevel, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(editDTimeout, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(btnGet)
                    .add(editEIQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(btnSet)
                    .add(editVIQ, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(editMaxFinger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(editSPFinger, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(editDTimeout, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(comboSLevel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Device functions"));

        jLabel7.setText("Device");

        btnOpen.setText("OPEN");
        btnOpen.setEnabled(false);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 41, Short.MAX_VALUE)
                .add(comboDevice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(btnOpen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(comboDevice, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnOpen))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Enroll & Capture"));

        jLabel8.setText("PayLoad");

        btnEnroll.setText("Enroll");
        btnEnroll.setEnabled(false);
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnCapture.setText("Capture");
        btnCapture.setEnabled(false);
        btnCapture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptureActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jLabel8)
                        .add(32, 32, 32)
                        .add(editPayload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                        .add(btnEnroll, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnCapture, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(editPayload, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnEnroll))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCapture)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Verify"));

        jLabel9.setText("Data Type");

        btnFIRType.add(rbtnBFIR);
        rbtnBFIR.setText("Use Binary FIR");

        btnFIRType.add(rbtnTFIR);
        rbtnTFIR.setText("Use Text FIR");

        btnFIRType.add(rbtnHFIR);
        rbtnHFIR.setText("Use HANDLE FIR");

        btnVerify.setText("Verify");
        btnVerify.setEnabled(false);
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        btnVerifyMatch.setText("VerifyMatch");
        btnVerifyMatch.setEnabled(false);
        btnVerifyMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyMatchActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .add(35, 35, 35)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(rbtnBFIR)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 148, Short.MAX_VALUE)
                        .add(btnVerify, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rbtnHFIR)
                            .add(rbtnTFIR))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 138, Short.MAX_VALUE)
                        .add(btnVerifyMatch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(rbtnBFIR)
                    .add(btnVerify))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(rbtnTFIR)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(rbtnHFIR))
                    .add(btnVerifyMatch))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        labelStatus.setText("No Error");
        labelStatus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1.setText("File");

        jMenuItem1.setText("SetSkinResource");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, labelStatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        labelStatus.setText("SetSkinResource Method start");

        String szPath = "";
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();

        if (fc.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION)  {
            java.io.File f = fc.getSelectedFile();

            szPath = f.getPath();

            bsp.SetSkinResource(szPath);

            if (CheckError())
                return ;

            labelStatus.setText("SetSkinResource Method OK");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
       labelStatus.setText("NBioBSP GetInitInfo start");

       NBioBSPJNI.INIT_INFO_0 initInfo0 = bsp.new INIT_INFO_0();
       bsp.GetInitInfo(initInfo0);

       if (CheckError())
            return ;

       editEIQ.setText(String.valueOf(initInfo0.EnrollImageQuality));
       editVIQ.setText(String.valueOf(initInfo0.VerifyImageQuality));
       editMaxFinger.setText(String.valueOf(initInfo0.MaxFingersForEnroll));
       editSPFinger.setText(String.valueOf(initInfo0.SamplesPerFinger));
       editDTimeout.setText(String.valueOf(initInfo0.DefaultTimeout));
       comboSLevel.setSelectedIndex(initInfo0.SecurityLevel - 1);

       labelStatus.setText("NBioBSP GetInitInfo success");
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetActionPerformed
        labelStatus.setText("NBioBSP SetInitInfo start");

        NBioBSPJNI.INIT_INFO_0 initInfo0 = bsp.new INIT_INFO_0();
        bsp.GetInitInfo(initInfo0);

        if (CheckError())
            return ;

        String szValue = "";

        try {
            szValue = editEIQ.getText();
            initInfo0.EnrollImageQuality = Integer.parseInt(szValue);

            szValue = editVIQ.getText();
            initInfo0.VerifyImageQuality = Integer.parseInt(szValue);

            szValue = editMaxFinger.getText();
            initInfo0.MaxFingersForEnroll = Integer.parseInt(szValue);

            szValue = editSPFinger.getText();
            initInfo0.SamplesPerFinger = Integer.parseInt(szValue);

            szValue = editDTimeout.getText();
            initInfo0.DefaultTimeout = Integer.parseInt(szValue);
        }
        catch (NumberFormatException e) {
            labelStatus.setText("Invalid Input value");
            return ;
        }

        initInfo0.SecurityLevel = comboSLevel.getSelectedIndex() + 1;

        bsp.SetInitInfo(initInfo0);

        if (CheckError())
            return ;

        labelStatus.setText("NBioBSP SetInitInfo success");
    }//GEN-LAST:event_btnSetActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        labelStatus.setText("NBioBSP OpenDevice start");

        if (openedDevice != 0)
            bsp.CloseDevice(openedDevice);

        openedDevice = 0;

        int nSelectedIndex = comboDevice.getSelectedIndex();

        if (nSelectedIndex == 0)
            bsp.OpenDevice();
        else  {
            nSelectedIndex -= 1;
            bsp.OpenDevice(deviceEnumInfo.DeviceInfo[nSelectedIndex].NameID, deviceEnumInfo.DeviceInfo[nSelectedIndex].Instance);
        }

        if (CheckError())
            return ;

        openedDevice = bsp.GetOpenedDeviceID();
        btnEnroll.setEnabled(true);
        btnCapture.setEnabled(true);

        labelStatus.setText("NBioBSP OpenDevice success");
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        labelStatus.setText("NBioBSP Enroll Start");

        if (hSavedFIR != null)  {
            hSavedFIR.dispose();
            hSavedFIR = null;
        }

        NBioBSPJNI.FIR_PAYLOAD payLoad;
        String szValue;

        szValue = editPayload.getText();
        payLoad = bsp.new FIR_PAYLOAD();

        if (szValue.length() > 0)
            payLoad.SetText(szValue);

        hSavedFIR = bsp.new FIR_HANDLE();

        bsp.Enroll(null, hSavedFIR, (szValue.length() > 0) ? payLoad : null, -1, null, null);

        if (CheckError())
            return ;

        if (fullSavedFIR != null)
            fullSavedFIR = null;

        if (textSavedFIR != null)
            textSavedFIR = null;

        fullSavedFIR = bsp.new FIR();
        bsp.GetFIRFromHandle(hSavedFIR, fullSavedFIR);

        if (CheckError())
            return ;

        textSavedFIR = bsp.new FIR_TEXTENCODE();
        bsp.GetTextFIRFromHandle(hSavedFIR, textSavedFIR);

        if (CheckError())
            return ;

        btnVerify.setEnabled(true);
        btnVerifyMatch.setEnabled(true);

        labelStatus.setText("NBioBSP Enroll success");
    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnCaptureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptureActionPerformed
        labelStatus.setText("NBioBSP Capture start");

        if (hSavedFIR != null)  {
            hSavedFIR.dispose();
            hSavedFIR = null;
        }

        hSavedFIR = bsp.new FIR_HANDLE();

        bsp.Capture(hSavedFIR);

        if (CheckError())
            return ;

        if (fullSavedFIR != null)
            fullSavedFIR = null;

        if (textSavedFIR != null)
            textSavedFIR = null;

        fullSavedFIR = bsp.new FIR();
        bsp.GetFIRFromHandle(hSavedFIR, fullSavedFIR);

        if (CheckError())
            return ;

        textSavedFIR = bsp.new FIR_TEXTENCODE();
        bsp.GetTextFIRFromHandle(hSavedFIR, textSavedFIR);

        if (CheckError())
            return ;

        btnVerify.setEnabled(true);
        btnVerifyMatch.setEnabled(true);
        
        labelStatus.setText("NBioBSP Capture success");
    }//GEN-LAST:event_btnCaptureActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        labelStatus.setText("NBioBSP Verify start");

        NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();
        Boolean bResult = new Boolean(false);
        NBioBSPJNI.FIR_PAYLOAD payload = bsp.new FIR_PAYLOAD();

        if (btnFIRType.isSelected(rbtnHFIR.getModel()))  {
            inputFIR.SetFIRHandle(hSavedFIR);
        }
        else if (btnFIRType.isSelected(rbtnBFIR.getModel()))  {
            inputFIR.SetFullFIR(fullSavedFIR);
        }
        else  {
            inputFIR.SetTextFIR(textSavedFIR);
        }

        bsp.Verify(inputFIR, bResult, payload);

        if (CheckError())
            return ;

        if (bResult)
            labelStatus.setText("Verify OK - Payload: " + payload.GetText());
        else
            labelStatus.setText("Verify Failed");
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnVerifyMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyMatchActionPerformed
        labelStatus.setText("NBioBSP VerifyMatch start");

        NBioBSPJNI.INPUT_FIR inputFIR = bsp.new INPUT_FIR();
        NBioBSPJNI.INPUT_FIR inputFIR2 = bsp.new INPUT_FIR();
        NBioBSPJNI.FIR_HANDLE hCapture = bsp.new FIR_HANDLE();
        Boolean bResult = new Boolean(false);
        NBioBSPJNI.FIR_PAYLOAD payload = bsp.new FIR_PAYLOAD();

        if (btnFIRType.isSelected(rbtnHFIR.getModel()))  {
            inputFIR.SetFIRHandle(hSavedFIR);
        }
        else if (btnFIRType.isSelected(rbtnBFIR.getModel()))  {
            inputFIR.SetFullFIR(fullSavedFIR);
        }
        else  {
            inputFIR.SetTextFIR(textSavedFIR);
        }

        bsp.Capture(hCapture);

        if (CheckError())
            return ;

        inputFIR2.SetFIRHandle(hCapture);
        bsp.VerifyMatch(inputFIR2, inputFIR, bResult, payload);

        if (CheckError())
            return ;

        if (bResult)
            labelStatus.setText("Verify OK - Payload: " + payload.GetText());
        else
            labelStatus.setText("Verify Failed");
    }//GEN-LAST:event_btnVerifyMatchActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NBioAPI_JavaDemo dialog = new NBioAPI_JavaDemo(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    }

    // Variable BSP
    private NBioBSPJNI                      bsp;
    private NBioBSPJNI.DEVICE_ENUM_INFO     deviceEnumInfo;
    private short                           openedDevice;
    private NBioBSPJNI.FIR_HANDLE           hSavedFIR;
    private NBioBSPJNI.FIR                  fullSavedFIR;
    private NBioBSPJNI.FIR_TEXTENCODE       textSavedFIR;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapture;
    private javax.swing.JButton btnEnroll;
    private javax.swing.ButtonGroup btnFIRType;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSet;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton btnVerifyMatch;
    private javax.swing.JComboBox comboDevice;
    private javax.swing.JComboBox comboSLevel;
    private javax.swing.JTextField editDTimeout;
    private javax.swing.JTextField editEIQ;
    private javax.swing.JTextField editMaxFinger;
    private javax.swing.JTextField editPayload;
    private javax.swing.JTextField editSPFinger;
    private javax.swing.JTextField editVIQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JRadioButton rbtnBFIR;
    private javax.swing.JRadioButton rbtnHFIR;
    private javax.swing.JRadioButton rbtnTFIR;
    // End of variables declaration//GEN-END:variables

}
