INSERT INTO country (name) VALUES ('Brasil');

INSERT INTO state (name, abbreviation, country_id) VALUES 
('Acre', 'AC', (Select id FROM country WHERE name = 'Brasil')), 
('Alagoas', 'AL', (Select id FROM country WHERE name = 'Brasil')), 
('AmapÃ¡', 'AP', (Select id FROM country WHERE name = 'Brasil')), 
('Amazonas', 'AM', (Select id FROM country WHERE name = 'Brasil')), 
('Bahia', 'BA', (Select id FROM country WHERE name = 'Brasil')), 
('CearÃ¡', 'CE', (Select id FROM country WHERE name = 'Brasil')), 
('Distrito Federal', 'DF', (Select id FROM country WHERE name = 'Brasil')), 
('EspÃ­rito Santo', 'ES', (Select id FROM country WHERE name = 'Brasil')), 
('GoiÃ¡s', 'GO', (Select id FROM country WHERE name = 'Brasil')), 
('MaranhÃ£o', 'MA', (Select id FROM country WHERE name = 'Brasil')), 
('Mato Grosso', 'MT', (Select id FROM country WHERE name = 'Brasil')), 
('Mato Grosso do Sul', 'MS', (Select id FROM country WHERE name = 'Brasil')), 
('Minas Gerais', 'MG', (Select id FROM country WHERE name = 'Brasil')), 
('ParÃ¡', 'PA', (Select id FROM country WHERE name = 'Brasil')), 
('ParaÃ­ba', 'PB', (Select id FROM country WHERE name = 'Brasil')), 
('ParanÃ¡', 'PR', (Select id FROM country WHERE name = 'Brasil')), 
('Pernambuco', 'PE', (Select id FROM country WHERE name = 'Brasil')), 
('PiauÃ­', 'PI', (Select id FROM country WHERE name = 'Brasil')), 
('Rio de Janeiro', 'RJ', (Select id FROM country WHERE name = 'Brasil')), 
('Rio Grande do Norte', 'RN', (Select id FROM country WHERE name = 'Brasil')), 
('Rio Grande do Sul', 'RS', (Select id FROM country WHERE name = 'Brasil')), 
('RondÃ´nia', 'RO', (Select id FROM country WHERE name = 'Brasil')), 
('Roraima', 'RR', (Select id FROM country WHERE name = 'Brasil')), 
('Santa Catarina', 'SC', (Select id FROM country WHERE name = 'Brasil')), 
('SÃ£o Paulo', 'SP', (Select id FROM country WHERE name = 'Brasil')), 
('Sergipe', 'SE', (Select id FROM country WHERE name = 'Brasil')), 
('Tocantins', 'TO', (Select id FROM country WHERE name = 'Brasil'));
