<?php
$title = $this->translate("Project");
$this->title = $title . ' - ' . $this->project->name;
$this->headTitle($this->translate("Project"));

$editDetailsUrl = $this->url(array(
    'module' => 'project',
    'controller' => 'admin',
    'action' => 'update',
    'id' => $this->project->id,
        ));

$pdfUrl = $this->url(array(
    'module' => 'project',
    'controller' => 'admin',
    'action' => 'pdf-project',
    'id' => $this->project->id,
        ));
?>

<div class="window">
    <div class="window-header">
        <div class="row">
            <h3 class="span6"><i class="icon-folder-close"></i> <?= $this->title; ?></h3>

            <ul class="nav nav-pills hidden-print pull-right">
                <li>
                    <a  href="<?= $editDetailsUrl; ?>" load-in="content-container"><i class="icon-edit"></i> <translate>Edit details</translate></a>
                </li>
                <li class="dropdown">
                    <a  class="dropdown-toggle" data-toggle="dropdown"
                        href="#" >
                        <i class="icon-print"></i> <translate>Print</translate>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        <li>
                            <a href="#" rel="print-window">
                                <i class="icon-desktop"></i> <translate>Screen</translate>
                            </a>
                        </li>
                        <li>
                            <a href="<?= $pdfUrl; ?>">
                                <i class="icon-file-alt"></i> <translate>Formated PDF</translate>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>

        </div>
    </div>
    <div class="window-content">
        <div class="details-bordered">
            <div class="row">
                <h3 class="span12 fn id alert alert-heading alert-info">
                    <?= $this->project->getName(); ?>
                </h3>
            </div>

            <div class="row">
                <?= $this->projectStatus()->html($this->project->getStatus(), array('class'=>'span2', 'tag'=>'div')); ?>
            </div>
            
            <div class="row">
                <h6 class="span2"><translate>Start date expected</translate></h6>
                <span class="span2">
                    <?= $this->date($this->project->startdateexpected, Zend_Date::DATE_SHORT); ?> 
                </span>
                <h6 class="span2"><translate>Finish date expected</translate></h6>
                <span class="span2">
                    <?= $this->date($this->project->finishdateexpected, Zend_Date::DATE_SHORT); ?> 
                </span>
            </div>    

            <div class="row">
                <h6 class="span2"><translate>Start date real</translate></h6>
                <span class="span2">
                    <?= $this->date($this->project->startdatereal, Zend_Date::DATE_SHORT); ?> 
                </span>
                <h6 class="span2"><translate>Finish date real</translate></h6>
                <span class="span2">
                    <?= $this->date($this->project->finishdatereal, Zend_Date::DATE_SHORT); ?> 
                </span>
            </div>    

            <div class="row">
                <div class="accordion span12" id="accordion-abstract">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-abstract" href="#abstract">
                                <translate>Abstract</translate>
                            </a>
                        </div>
                        <div id="abstract" class="accordion-body collapse in">
                            <div class="accordion-inner">
                                <?= nl2br($this->project->abstract); ?> 
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-fulldescription" href="#fulldescription">
                                <translate>Full description</translate>
                            </a>
                        </div>
                        <div id="fulldescription" class="accordion-body collapse out">
                            <div class="accordion-inner">
                                <?= $this->project->fulldescription; ?> 
                            </div>
                        </div>
                    </div>
                </div>
<!--                <h6 class="span2"><translate>Abstract</translate></h6>
                <span class="span10">
                <?= nl2br($this->project->abstract); ?> 
                </span>-->
            </div>

        </div>            
    </div>
</div>