<?php

require_once dirname(__FILE__) . '/../../../../lib/Agana/Version.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-20 at 02:41:35.
 */
class Agana_VersionTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Agana_Version
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Agana_Version;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Agana_Version::getFrameworkVersion
     */
    public function testGetFrameworkVersion() {
        $this->assertTrue($this->object->getFrameworkVersion() != '');
    }

    /**
     * @covers Agana_Version::getFrameworkDeployDate
     */
    public function testGetFrameworkDeployDate() {
        $this->assertTrue($this->object->getFrameworkDeployDate() != '');
    }

    /**
     * @covers Agana_Version::getAppVersion
     * @todo   Implement testGetAppVersion().
     */
    public function testGetAppVersion() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Agana_Version::getAppDeployDate
     * @todo   Implement testGetAppDeployDate().
     */
    public function testGetAppDeployDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
