<?php
$title = $this->translate("Upload image");
$this->title = $title;
$this->headTitle($this->translate("Upload image"));
?>

<div class="row">
    <div class="widget">
        <div class="widget-header">
            <h3 class="span6">
                <i class="icon-camera"></i> <translate>Upload image</translate>
            </h3>
            <i class="icon-question-sign span1" rel="popover" 
               data-placement="bottom" 
               title="<translate>Alter image</translate>" 
               data-content="- <translate>Allowed file extensions</translate>: jpg, jpeg, png <br/>- <translate>Allowed max file size</translate>: 100 Kb">
            </i>
        </div>
        <div class="widget-content">
            <div class="span3">
                <form class="" id="formUpload" method="post" 
                      enctype="multipart/form-data action="<?php echo $this->actionUrl; ?>">
                      <input class="btn span2" type="file" name="uploadFile" id="uploadFile">
                </form>

                <a class="btn btn-info" id="btnUploadFile">
                    <i class="icon-upload-alt"></i> <translate>Upload choosed file</translate>
                </a>
                <hr />
                <div class="alert hide" id="uploadingFileMsg">
                    <i class="icon-upload-alt"></i> <translate>sending file</translate> ....
                </div>
                <div class="alert alert-success hide" id="uploadedFileMsg">
                </div>
            </div>
            <div class="span4 picture thumbnail">
                <img src="" id="uploadedImage" style="height: 300px"/>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="<?php echo $this->baseUrl() . $this->path_vendor . '/ajaxfileupload.js'; ?>"></script>
<script type="text/javascript" >
    var actionUrl = "<?php echo $this->actionUrl; ?>";
                
    var mediaBaseUrl = "<?php
echo $this->url(array(
    'module' => 'media', 'controller' => 'image', 'action' => 'get',
        ), null, true);
?>";
    
    var elImgToUpdate = "<?php echo $this->elImgToUpdate; ?>";


    var fileElId = 'uploadFile';
    var elReturnMsg = $('#uploadedFileMsg');
    var elUpLoadImageDialog = $('#uploadImageDialog');

    // only loads image on dialog box if needs
    $('#uploadedImage').attr('src', '<?php echo $this->imgSrc;?>');

    $(elUpLoadImageDialog).on('hide', function(){
        // loads image on profile
        $('#userImage').attr('src', $('#uploadedImage').attr('src'));
    });

    $('#btnUploadFile').bind('click', function(ev){
        $(elReturnMsg).hide();
        $("#uploadingFileMsg").fadeIn();

        $.ajaxFileUpload ({
            url: actionUrl,
            secureuri:false,
            fileElementId: fileElId,
            dataType: 'json',
            data:{name:'logan', id:'id'},
            handleError: function(data) {
                console.info(data);
                $(elReturnMsg).addClass('alert-error');
                $("#uploadingFileMsg").fadeOut('fast',function(){
                    $(elReturnMsg).html(data.responseText);
                    $(elReturnMsg).fadeIn('show'); 
                });
            },
            success: function (data, status) {                       
                console.info(data);
                var returnMsg = '';
                if(typeof(data.error) == 'undefined') {
                    returnMsg += data.file.type + '<br/>';
                    //returnMsg += '<translate>File name</translate>:' + data.file.name + '<br/>';
                    returnMsg += '<translate>File size</translate>:' + data.file.size;                            
                    $('#uploadedImage').attr('src', mediaBaseUrl + '/file/' + data.file.name);
                    
                    if (elImgToUpdate) {
                        $('#'+elImgToUpdate).attr('src', mediaBaseUrl + '/file/' + data.file.name);
                    }
                } else {                            
                    if(data.error != '') {
                        if (data.error instanceof Array) {
                            for (var i in data.error) {
                                returnMsg += data.error[i] + '<br/>';
                            }
                        } else {
                            returnMsg = data.error;
                        }
                    } else {
                        returnMsg = data.msg;
                    }
                    $(elReturnMsg).addClass('alert-error');
                }

                $("#uploadingFileMsg").fadeOut('fast',function(){
                    $(elReturnMsg).html(returnMsg);
                    $(elReturnMsg).fadeIn('show'); 
                });
            },
            error: function (data, status, e) {
                alert(e);
            }
        });

        return false;
    });
</script>