<?php
$title = $this->translate("User");
$this->title = $title . ' ' . $this->user->getName() . ' - ' . $this->translate("Change password");
$this->headTitle($this->translate("User"));
$form = new Zend_Form();
$form = $this->form;
$form->setAction($this->url());
?>

<div class="window">
    <div class="window-header">
        <h3><i class="icon-user"></i> <?php echo $this->title; ?> </h3>
    </div>
    <div class="window-content">
        <h6 class="offset2"><?php echo $this->user->getName(); ?></h6>
    </div>
    <?php echo $this->form->render(); ?>
</div>
