<?php

require_once  dirname(__FILE__) .'/../../../../../../agana/lib/Agana/Util/DateTime.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-02 at 16:30:46.
 */
class Agana_Util_DateTimeTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Agana_Util_DateTime
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Agana_Util_DateTime;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Agana_Util_DateTime::dateToYYMMDD
     * @todo   Implement testDateToYYMMDD().
     */
    public function testDateToYYMMDD() {
        $this->assertEquals("131220", $this->object->dateToYYMMDD("20/12/2013", ''));
    }

    /**
     * @covers Agana_Util_DateTime::timestampToScrambleChars
     * @todo   Implement testTimestampToScrambleChars().
     */
    public function testTimestampToScrambleChars() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Agana_Util_DateTime::scrambledCharsToTimestamp
     * @todo   Implement testScrambledCharsToTimestamp().
     */
    public function testScrambledCharsToTimestamp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
