<?php
$title = $this->translate("Reset password");
$this->title = $title;
$this->headTitle($title);
$form = $this->form;
$form->setAction($this->url());
?>

<div id="login-container" class="container">
    <div id="login-inner-container" class="span7 well well-large">
        <div class="row">
        <h2 class="span4">ONG online</h2>
        <hr/>
        <h3 class="span8"><i class="icon-lock"></i> 
            <?php echo $title; ?>
        </h3>
    </div>
    <div class="well">
        <?php echo $this->form->render(); ?>
        <script>
            $('form').removeAttr('load-in');
        </script>
    </div>
</div>
