<!DOCTYPE html>
<?php
$appName = '';
if (Zend_Auth::getInstance()->hasIdentity()) {
    $auth = Zend_Auth::getInstance()->getIdentity();
    $ud = new User_Domain_User();
    $auth = $ud->getById($auth->id);
    $appName = $auth->getAppAccount()->getName();
}

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');
$this->headMeta()->appendName('description', 'Software para controle de academias e estúdios de treinamento pessoal ou nutricionista');
$this->headMeta()->appendName('author', 'Winponta Software');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Winponta Health Studio Manager');
echo $this->doctype() . PHP_EOL;
?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br"
      class="app">
    <head>
        <?php
        echo $this->headMeta() . PHP_EOL;
        echo $this->headTitle() . PHP_EOL;

        // favicon
        echo '<link rel="icon" type="image/png" href="' . $this->baseUrl() . $this->path_img . '/favicon.png">';
        echo PHP_EOL;

        // CSS
        $this->headLink()->appendStylesheet($this->baseUrl() . $this->path_vendor . "/colorbox/colorbox.css", "screen");
        $this->headLink()->appendStylesheet($this->baseUrl() . $this->path_vendor . "/jquery-ui/css/jquery-ui-1.9.1.custom.min.css", "screen");
        $this->headLink()->appendStylesheet($this->baseUrl() . $this->path_css . "/main.css", "screen");
        $this->headLink()->appendStylesheet($this->baseUrl() . $this->path_vendor . "/agana/css/agana.cool.messages.css", "screen");
        echo $this->headLink();
        echo PHP_EOL;

        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/agana/js/agana.bootstrap.js");
        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/agana/js/agana.gm.js");
        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/agana/js/agana.overlay.js");
        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/agana/js/agana.app.js");
//        $this->headScript()->prependFile($this->baseUrl() . $this->path_js . "/aganaCoolMessage.js");

        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/jquery-ui/js/jquery-ui-1.9.1.custom.min.js");
        
        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/colorbox/jquery.colorbox-min.js");

        $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/twitter-bootstrap/js/bootstrap.min.js");

        if (APPLICATION_ENV == 'production') {
            $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
        } else {
            $this->headScript()->prependFile($this->baseUrl() . $this->path_vendor . "/jquery/jquery-1.7.2.js");
        }

//        if ($this->dojo()->isEnabled()) {
//            $dojoMenu = $this->dojoMenu($menu);
//            $dojoMenuElement = $dojoMenu->renderMenu($menu);
//
//            //$this->dojo()->setLocalPath($this->baseUrl() . '/themes/resouces/dojo/dojo/dojo.js')
//            $this->dojo()->setDjConfigOption('usePlainJson', true)
//                    ->setDjConfigOption('parseOnLoad', true)
//                    ->setLocalPath('http://localhost/Desenvolvimento/Winponta/resources/dojo/1.7.1/dojo/dojo.js')
//                    ->addStyleSheetModule('dijit.themes.claro')
//            ;
//            //->setUseDeclarative();
//            echo $this->dojo();
//        }

        echo $this->headScript();
        echo PHP_EOL;
        ?>
    </head>
    <body class="app">
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <!--                    <a id="appBrand" class="brand span2" href=".">
                                            Health Studio
                                            <span class="slogan">Management</span>
                                        </a>                 -->


                    <div id="menu-container">
                        <?php
                        if (Zend_Auth::getInstance()->hasIdentity()) {
                            //$menu = new Agana_Navigation_Container();
                            //$menu->loadMenu();

                            $globalMenu = Zend_Registry::get('Navigation.GlobalMenu');
                            ?>

                            <?php
                            $nav = $this->navigation($globalMenu);
                            echo $this->iconify($nav->menu()
                                            ->setUlClass('nav nav-pills')
                                            ->renderMenu()
                            );
                            //echo $menu;
                            //echo $menu->renderMenu();
                            ?>
                        <?php } ?>
                    </div>
                    <div class="nav-collapse pull-right">
                        <ul class="nav nav-pills">
                            <li class="dropdown">                                    
                                <a data-toggle="dropdown" class="dropdown-toggle">
                                    <i class="icon-user"></i>&nbsp;
                                    <?php echo $this->userName(); ?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php if ($this->userName()) { ?>
                                        <li>
                                            <a href="<?php
                                    echo $this->url(array(
                                        'module' => 'user',
                                        'controller' => 'profile',
                                        'action' => 'index'), null, true);
                                        ?>"
                                               load-in="content-container">
                                                <i class="icon-user"></i>
                                                <translate>Profile</translate>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="<?php
                                           echo $this->url(array(
                                               'module' => 'app',
                                               'controller' => 'account',
                                               'action' => 'index'), null, true);
                                        ?>"
                                               load-in="content-container">
                                                <i class="icon-certificate"></i>
                                                <translate>App Account</translate>
                                            </a>
                                        </li>
                                    </ul>
                                <?php } ?>
                                <li>
                                    <a href="<?php
                                echo $this->url(array(
                                    'module' => 'aganacore',
                                    'controller' => 'index',
                                    'action' => 'about'), 'default', true);
                                ?>" id="app-about" rel="colorbox" title="About">
                                        <i class="icon-info-sign"> </i>
                                        <translate>About</translate>
                                    </a>
                                </li>
                                <li>                                        
                                    <?php
                                    echo ' ' .
                                    $this->loginOutLink('Login', 'Logout', true, '<i class="icon-signin"></i> ', '', '<i class="icon-signout"></i> ', '', 'load-in="content-container"'
                                    );
                                    ?>
                                </li>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div id="main" class="container-fluid">

            <div id="content-container" class="container-fluid">
                <!--                <div class="container-fluid">                
                <?php echo $this->flashMessages(); ?>
                                </div>-->

                <div id="content">
                    <?php if (trim($this->escape($this->title)) != '') { ?>
                        <!--                        <header>
                                                    <h1><?php echo $this->escape($this->title); ?></h1>
                                                </header>-->
                    <?php } ?>

                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>

        <div id="footerSlideContainer">
            <div id="footerSlideButton"><i class="icon-caret-up"></i></div>
            <div id="footerSlideContent">
                <div id="footerSlideText">
                    powered by <a href="http://www.winponta.com.br" target="_blank"> <img src="<?php echo $this->baseUrl() . $this->path_img . '/favicon.png' ?>"/> Winponta Software</a>  |  <a href="<?php echo $this->url(array('pagename' => 'credits'), "pageRoute", false); ?>"><img src="<?php echo $this->baseUrl() . $this->path_img . '/blocks.png' ?>"/> créditos</a>
                </div>
            </div>
        </div>
    </body>
</html>
